DROP DATABASE IF EXISTS Tutorat;
CREATE DATABASE IF NOT EXISTS Tutorat;
USE Tutorat;

CREATE TABLE IF NOT EXISTS USER(
	USER_ID INT(11) AUTO_INCREMENT PRIMARY KEY,
	DEA INT(7),
	FIRST_NAME VARCHAR(255),
	LAST_NAME VARCHAR(255),
	EMAIL VARCHAR(50),
	ROLE VARCHAR(20),
	HORAIRE TEXT,
	UNIQUE(EMAIL),
	UNIQUE(DEA)
);

CREATE TABLE IF NOT EXISTS COURS(
	COURS_ID INT(11) AUTO_INCREMENT PRIMARY KEY,
	TUTEUR_ID INT(11),
	ETUDIANT_ID INT(11),
	FOREIGN KEY (TUTEUR_ID) REFERENCES USER (USER_ID),
	FOREIGN KEY (ETUDIANT_ID) REFERENCES USER (USER_ID)
);

CREATE TABLE IF NOT EXISTS SESSIONS(
	SESSION_ID INT(11) AUTO_INCREMENT PRIMARY KEY,
	COURS_ID INT(11),
	MESSAGES TEXT,
	DATE_SESSION DATE,
	FOREIGN KEY (COURS_ID) REFERENCES COURS (COURS_ID)
);

CREATE TABLE IF NOT EXISTS EVALSFINS(
  EVALUATION_ID INT(11) AUTO_INCREMENT PRIMARY KEY,
  NOTE_FINALE INT(11),
  COMMENTAIRE TEXT,
  REUSSITE BOOLEAN,
  ETUDIANT_ID INT(11),
  TUTEUR_ID INT(11),
  FOREIGN KEY (ETUDIANT_ID) REFERENCES USER(USER_ID),
  FOREIGN KEY (TUTEUR_ID) REFERENCES USER(USER_ID)
);

CREATE TABLE IF NOT EXISTS HIDDEN (
	USER_ID INT(11),
	hiddenPass VARCHAR(30),
	FOREIGN KEY (USER_ID) REFERENCES USER(USER_ID)
);
