DROP DATABASE IF EXISTS Tutorat;
CREATE DATABASE IF NOT EXISTS Tutorat;
USE Tutorat;


CREATE TABLE IF NOT EXISTS ETUDIANTS(
  ETUDIANT_ID INT(11) AUTO_INCREMENT PRIMARY KEY,
  NOM VARCHAR(30),
  PRENOM VARCHAR(30),
  COURS VARCHAR(30),
  HORAIRE VARCHAR(30)
);

CREATE TABLE IF NOT EXISTS TUTEURS(
  TUTEUR_ID INT(11) AUTO_INCREMENT PRIMARY KEY,
  NOM VARCHAR(30),
  PRENOM VARCHAR(30),
  COURS_DONNE VARCHAR(30)
);


CREATE TABLE IF NOT EXISTS EVALUATION(
  EVALUATION_ID INT(11) AUTO_INCREMENT PRIMARY KEY,
  NOTE_FINAL INT,
  COMMENTAIRE VARCHAR(30),
  REUSSIT BOOLEAN,
  ETUDIANT_ID INT,
  TUTEUR_ID INT,
  FOREIGN KEY (ETUDIANT_ID) REFERENCES ETUDIANTS(ETUDIANT_ID),
  FOREIGN KEY (TUTEUR_ID) REFERENCES TUTEURS(TUTEUR_ID)
);


CREATE TABLE IF NOT EXISTS SESSION_TUTORAT(
  SESSION_ID INT(11) AUTO_INCREMENT PRIMARY KEY,
  COURS VARCHAR(30),
  SESSION_TUTORAT VARCHAR(30),
  COMMENTAIRE VARCHAR(30),
  COURS_TUTORAT VARCHAR(30),
  JOUR_DE_LA_SESSION DATE,
  ETUDIANT_ID INT,
  TUTEUR_ID INT,
  FOREIGN KEY (ETUDIANT_ID) REFERENCES ETUDIANTS(ETUDIANT_ID),
  FOREIGN KEY (TUTEUR_ID) REFERENCES TUTEURS(TUTEUR_ID)
);
