DROP DATABASE IF EXISTS GLYNN;
CREATE DATABASE IF NOT EXISTS GLYNN;
USE GLYNN;


DROP TABLE IF EXISTS GLYNN;

CREATE TABLE ETUDIANTS(
ETUDIANT_ID INT NOT NULL AUTO_INCREMENT,
NOM VARCHAR(30),
PRENOM VARCHAR(30),
COURS VARCHAR(30),
HORAIRE VARCHAR(30),
PRIMARY KEY (ETUDIANT_ID)
);

CREATE TABLE TUTEURS(
TUTEUR_ID INT NOT NULL AUTO_INCREMENT,
NOM VARCHAR(30),
PRENOM VARCHAR(30),
COURS_DONNE VARCHAR(30),
PRIMARY KEY (TUTEUR_ID)
)


CREATE TABLE EVALUATION(
EVALUATION_ID INT NOT NULL AUTO_INCREMENT,
NOTE_FINAL INT,
COMMENTAIRE VARCHAR(30),
REUSSIT BOOLEAN,
PRIMARY KEY (EVALUATION_ID)
FOREIGN KEY (ETUDIANT_ID) REFERENCES ETUDIANTS(ETUDIANT_ID)
FOREIGN KEY (TUTEUR_ID) REFERENCES TUTEURS(TUTEUR_ID)
)


CREATE TABLE SESSION_TUTORAT(
SESSION_ID INT NOT NULL AUTO_INCREMENT,
COURS VARCHAR(30),
SESSION_TUTORAT VARCHAR(30),
COMMENTAIRE VARCHAR(30),
COURS_TUTORAT VARCHAR(30),
JOUR_DE_LA_SESSION DATE,
PRIMARY KEY (SESSION_ID)
FOREIGN KEY (ETUDIANT_ID) REFERENCES ETUDIANTS(ETUDIANT_ID)
FOREIGN KEY (TUTEUR_ID) REFERENCES TUTEURS(TUTEUR_ID)
)